# Generated by Django 4.1.4 on 2022-12-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boat_model', models.CharField(max_length=100)),
                ('engine', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('car_model', models.CharField(max_length=100)),
            ],
        ),
    ]
