name: Docker image CI

on:
  push:
    branches: [ "pr10" ]
jobs:
  build_and_push:      
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: docker build . --file Dockerfile -t timofeybelikov/ma-status-service2:latest
        
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          
      - name: Push tag to Docker Hub
        run: docker push timofeybelikov/ma-status-service2:latest
